import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createOrderSchema } from '@/lib/validation/schemas/order-schema'
import type { CreateOrderRequest } from '@/lib/types/database'

/**
 * POST /api/orders - Create a new order with items
 *
 * Request body:
 * {
 *   customer_name: string
 *   customer_phone?: string
 *   pickup_time: string (ISO datetime)
 *   source: 'whatsapp' | 'manual' | 'email' | 'phone'
 *   notes?: string
 *   items: [{ dish_id: string, quantity: number }]
 * }
 *
 * Response: { data: OrderWithItems } | { error: { code, message } }
 */
export async function POST(req: NextRequest) {
  try {
    const supabase = await createClient()

    // Parse and validate request body
    const body: CreateOrderRequest = await req.json()
    const validation = createOrderSchema.safeParse(body)

    if (!validation.success) {
      return NextResponse.json(
        {
          error: {
            code: 'VALIDATION_ERROR',
            message: 'Invalid request data',
            details: validation.error.flatten().fieldErrors,
          },
        },
        { status: 400 }
      )
    }

    const { items, ...orderData } = validation.data

    // Create order (order_number is auto-generated by SERIAL)
    const { data: order, error: orderError } = await supabase
      .from('orders')
      .insert({
        customer_name: orderData.customer_name,
        customer_phone: orderData.customer_phone || null,
        pickup_time: orderData.pickup_time,
        source: orderData.source,
        notes: orderData.notes || null,
      })
      .select()
      .single()

    if (orderError) {
      console.error('Order creation error:', orderError)
      return NextResponse.json(
        {
          error: {
            code: 'DATABASE_ERROR',
            message: 'Failed to create order',
            details: orderError.message,
          },
        },
        { status: 500 }
      )
    }

    // Create order items
    const orderItemsData = items.map((item) => ({
      order_id: order.id,
      dish_id: item.dish_id,
      quantity: item.quantity,
    }))

    const { error: itemsError } = await supabase
      .from('order_items')
      .insert(orderItemsData)

    if (itemsError) {
      // Rollback: delete the order if items creation fails
      await supabase.from('orders').delete().eq('id', order.id)

      console.error('Order items creation error:', itemsError)
      return NextResponse.json(
        {
          error: {
            code: 'DATABASE_ERROR',
            message: 'Failed to create order items',
            details: itemsError.message,
          },
        },
        { status: 500 }
      )
    }

    // Fetch complete order with items and dishes
    const { data: completeOrder, error: fetchError } = await supabase
      .from('orders')
      .select(`
        *,
        order_items (
          *,
          dish:dishes (*)
        )
      `)
      .eq('id', order.id)
      .single()

    if (fetchError) {
      console.error('Order fetch error:', fetchError)
      return NextResponse.json(
        {
          error: {
            code: 'DATABASE_ERROR',
            message: 'Order created but failed to fetch',
            details: fetchError.message,
          },
        },
        { status: 500 }
      )
    }

    return NextResponse.json({ data: completeOrder }, { status: 201 })
  } catch (error) {
    console.error('Unexpected error in POST /api/orders:', error)
    return NextResponse.json(
      {
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
        },
      },
      { status: 500 }
    )
  }
}

/**
 * GET /api/orders - List orders with optional filters
 *
 * Query params:
 * - status?: order_status enum value
 * - date?: ISO date string (filters by created_at date)
 * - limit?: number (default 50)
 * - offset?: number (default 0)
 *
 * Response: { data: OrderWithItems[], count: number, limit: number, offset: number } | { error: { code, message } }
 */
export async function GET(req: NextRequest) {
  try {
    const supabase = await createClient()
    const { searchParams } = new URL(req.url)

    const status = searchParams.get('status')
    const date = searchParams.get('date')
    const limit = parseInt(searchParams.get('limit') || '50', 10)
    const offset = parseInt(searchParams.get('offset') || '0', 10)

    let query = supabase
      .from('orders')
      .select(`
        *,
        order_items (
          *,
          dish:dishes (*)
        )
      `, { count: 'exact' })
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1)

    // Apply filters
    if (status) {
      query = query.eq('status', status)
    }

    if (date) {
      const startOfDay = new Date(date)
      startOfDay.setHours(0, 0, 0, 0)
      const endOfDay = new Date(date)
      endOfDay.setHours(23, 59, 59, 999)

      query = query
        .gte('created_at', startOfDay.toISOString())
        .lte('created_at', endOfDay.toISOString())
    }

    const { data: orders, error, count } = await query

    if (error) {
      console.error('Orders fetch error:', error)
      return NextResponse.json(
        {
          error: {
            code: 'DATABASE_ERROR',
            message: 'Failed to fetch orders',
            details: error.message,
          },
        },
        { status: 500 }
      )
    }

    return NextResponse.json({
      data: orders,
      count: count || 0,
      limit,
      offset,
    })
  } catch (error) {
    console.error('Unexpected error in GET /api/orders:', error)
    return NextResponse.json(
      {
        error: {
          code: 'INTERNAL_ERROR',
          message: 'An unexpected error occurred',
        },
      },
      { status: 500 }
    )
  }
}
